# Generated by Django 5.1.3 on 2024-12-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2024)),
                ('author', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('imageUrl', models.URLField(blank=True)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
